[[bugs]]
title = ""
description = ""

[[breaking]]
title = ""
description = ""

[[features]]
title = "New APIs"
description = "Several new endpoints in [#XXX](https://github.com/oxidecomputer/oxide.go/pull/XXX)\n  - NetworkingAllowListView: Get user-facing services IP allowlist \n  - NetworkingAllowListUpdate: Update user-facing services IP allowlist \n  - NetworkingSwitchPortStatus: Get switch port status"

[[enhancements]]
title = ""
description = ""