[[features]]
title = "New APIs"
description = "Several new endpoints in [#XXX](https://github.com/oxidecomputer/oxide.go/pull/XXX)\n  - VpcRouterRouteList: List routes \n  - VpcRouterRouteListAllPages: List routes \n  - VpcRouterRouteCreate: Create route \n - VpcRouterRouteView: Fetch route \n - VpcRouterRouteUpdate: Update route \n - VpcRouterRouteDelete: Delete route \n - VpcRouterList: List routers \n - VpcRouterListAllPages: List routers \n - VpcRouterCreate: Create VPC router \n - VpcRouterView: Fetch router \n - VpcRouterUpdate: Update router \n - VpcRouterDelete: Delete router"

[[breaking]]
title = ""
description = ""

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = ""
description = ""