[[breaking]]
title = "OneOf generic types"
description = "All struct field types that have different property types in the OpenAPI spec have now been set to `any`. [#234](https://github.com/oxidecomputer/oxide.go/pull/234)"

[[features]]
title = "Helper function"
description = "New `NewPointer` function that returns a pointer to a given value. [235](https://github.com/oxidecomputer/oxide.go/pull/235)"

[[enhancements]]
title = ""
description = ""

[[bugs]]
title = "Fix for fields of type `time.Time`"
description = "Change encoding of time parameters to RFC3339. [232](https://github.com/oxidecomputer/oxide.go/pull/232)"

[[bugs]]
title = "Fix for types"
description = "Account for additional fields 'array' types that don't specify map keys. [235](https://github.com/oxidecomputer/oxide.go/pull/235)"

[[features]]
title = "New fields for Instance"
description = "It is now possible to specify a boot disk and update it. Additionally, instances now have 'autorestart' functionality, where if set the control plane to automatically restart it if it enters the `Failed` state. [236](https://github.com/oxidecomputer/oxide.go/pull/236)"

[[breaking]]
title = "NetworkingBgpAnnounceSet type"
description = "Small change in fields. [236](https://github.com/oxidecomputer/oxide.go/pull/236)"

[[features]]
title = "New types and methods"
description = "Create, list, view and delete methods for InternetGatewayIpAddress and InternetGatewayIpPool. [XXX](https://github.com/oxidecomputer/oxide.go/pull/XXX)"