[[bugs]]
title = ""
description = ""

[[enhancements]]
title = ""
description = ""

[[breaking]]
title = "Go version"
description = "Minimum required Go version has been updated to 1.21. [#179](https://github.com/oxidecomputer/oxide.go/pull/179)"

[[breaking]]
title = "NewClient API change"
description = "The `NewClient` function has been updated to no longer require a user agent parameter. [#180](https://github.com/oxidecomputer/oxide.go/pull/180)"

[[breaking]]
title = "NewClientFromEnv removal"
description = "The `NewClientFromEnv` function has been removed. Users should use `NewClient` instead. [#180](https://github.com/oxidecomputer/oxide.go/pull/180)"

[[features]]
title = "New APIs"
description = "Live attach and detach of external IPs to an instance. [#182](https://github.com/oxidecomputer/oxide.go/pull/182)"

[[features]]
title = "New APIs"
description = "Several silo IP pool maintenance endpoints. [#182](https://github.com/oxidecomputer/oxide.go/pull/182)"

[[breaking]]
title = "Method renames"
description = "Several methods have had slight name changes to better reflect their functionality.[#182](https://github.com/oxidecomputer/oxide.go/pull/182)"